FROM golang:1.18.3-alpine3.16 AS builder

WORKDIR /opt/go-dice-backend
COPY . .

RUN go install ./...

FROM alpine:3.16.0

COPY --from=builder /go/bin/go-dice-backend /usr/local/bin/go-dice-backend

CMD ["go-dice-backend"]
