version: "3"
services:
  go-dice-backend:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      PORT: 9090
    ports:
      - 8080:9090 # first - host port, second - container port (port mapping)
    restart: always
