version: "3"
services:
  k6:
    image: grafana/k6:0.39.0-69-g8f981bb3
    environment:
      - SERVICE_ADDRESS=localhost:8080
      - K6_OUT=influxdb=http://localhost:8086/k6,csv=/etc/go-dice-backend/outputs/output.csv
    ports:
      - 6565:6565 # first - host port, second - container port (port mapping)
    volumes:
      - ./tests/load_tests.js:/etc/go-dice-backend/load_tests.js:ro
      - ./tests/outputs:/etc/go-dice-backend/outputs
    entrypoint:
      - k6
      - run
      - /etc/go-dice-backend/load_tests.js
    network_mode: host

  influxdb:
    image: influxdb:1.8.10-alpine
    environment:
      - INFLUXDB_DB=k6
    ports:
      - 8086:8086 # first - host port, second - container port (port mapping)

  grafana:
    image: grafana/grafana:9.1.1
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/performance-test-dasboard.json
    ports:
      - 3000:3000 # first - host port, second - container port (port mapping)
    volumes:
      - ./tests/grafana:/etc/grafana/provisioning:ro
