version: "3"
services:
  nginx:
    image: nginx:1.25.1-alpine
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - SERVER_ADDRESS_1=${SERVER_ADDRESS_1-127.0.0.1:8081}
      - SERVER_ADDRESS_2=${SERVER_ADDRESS_2-127.0.0.1:8082}
    ports:
      - 8080:80 # first - host port, second - container port (port mapping)
    volumes:
      - ./load_balancing.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    restart: always
