version: "3"
services:
  go-dice-backend:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      PORT: 9090
    ports:
      - 8080:9090 # first - host port, second - container port (port mapping)
    restart: always

  swagger:
    image: swaggerapi/swagger-ui:v4.13.2
    environment:
      SWAGGER_JSON: /etc/go-dice-backend/swagger.json
    ports:
      - 9090:8080 # first - host port, second - container port (port mapping)
    volumes:
      - ./docs/swagger.json:/etc/go-dice-backend/swagger.json:ro
    restart: always

  k6:
    image: grafana/k6:0.39.0-69-g8f981bb3
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    ports:
      - 6565:6565 # first - host port, second - container port (port mapping)
    volumes:
      - ./tests/load_tests.js:/etc/go-dice-backend/load_tests.js:ro
    entrypoint:
      - k6
      - run
      - /etc/go-dice-backend/load_tests.js

  influxdb:
    image: influxdb:1.8.10-alpine
    environment:
      - INFLUXDB_DB=k6
    ports:
      - 8086:8086 # first - host port, second - container port (port mapping)

  grafana:
    image: grafana/grafana:9.1.1
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - 3000:3000 # first - host port, second - container port (port mapping)
    volumes:
      - ./tests/grafana:/etc/grafana/provisioning:ro

