version: "3"
services:
  go-dice-backend:
    build: 
      context: .
      dockerfile: DockerFile
    ports:
      - 8080:8080 # first - host port, second - container port (port mapping)
    restart: always
